// <auto-generated />
namespace Module6Tp1Dojo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deuxieme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deuxieme));
        
        string IMigrationMetadata.Id
        {
            get { return "202003231035339_deuxieme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
